var mongoose=require('mongoose');

var userSchema=mongoose.Schema(
    {
        userName:
        {
            type:String,
            required:true
        },
        password:
        {
            type:String,
            required:true
        },
        name:
        {
            type:String,
            required:true
        },
        email:
        {
            type:String,
            required:true
        },
        phone:
        {
            type:Number,
            required:true
        },
        empCode:
        {
            type:String,
            required:true
        },
        role:
        {
            roleId:String,
            roleName:String
        },
        department:
        {
            departmentId:String,
            departmentName:String
        },
        isLoggedIn:Boolean,
        status:
        {
            type:Boolean,
            required:true
        },
        family:
        {   familyId:String 
        },
        FCMToken:String,
        created:
        {
            type:Date,
            default:Date.now
        },
        lastUpdated:
        {
            type:Date 
        },
        createdBy:
        {
            type:String,
            required:true
        },
        lastUpdatedBy:
        {
            type:String,
            required:true
        }
    }
);

var User=module.exports=mongoose.model('users',userSchema);